export const state = () => ({
  countries: [
    {
      id: 1,
      name: "السعودية",
      description: null,
      code: "sa",
      phone_code: "00966",
      flag: "🇸🇦",
      phone_available: true,
      target_available: true,
      destination_available: false,
    },
    {
      id: 2,
      name: "مصر",
      description: null,
      code: "eg",
      phone_code: "0020",
      flag: "🇪🇬",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 3,
      name: "أفغانستان",
      description: null,
      code: "af",
      phone_code: "0093",
      flag: "🇦🇫",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 4,
      name: "ألبانيا",
      description: null,
      code: "al",
      phone_code: "00355",
      flag: "🇦🇱",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 5,
      name: "الجزائر",
      description: null,
      code: "dz",
      phone_code: "00213",
      flag: "🇩🇿",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 6,
      name: "أندورا",
      description: null,
      code: "ad",
      phone_code: "00376",
      flag: "🇦🇩",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 7,
      name: "أنجولا",
      description: null,
      code: "ao",
      phone_code: "00244",
      flag: "🇦🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 8,
      name: "أنتركتيكا",
      description: null,
      code: "aq",
      phone_code: "00672",
      flag: "🇦🇶",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 9,
      name: "الأرجنتين",
      description: null,
      code: "ar",
      phone_code: "0054",
      flag: "🇦🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 10,
      name: "أرمينيا",
      description: null,
      code: "am",
      phone_code: "00374",
      flag: "🇦🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 11,
      name: "آروبا",
      description: null,
      code: "aw",
      phone_code: "00297",
      flag: "🇦🇼",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 12,
      name: "استراليا",
      description: null,
      code: "au",
      phone_code: "0061",
      flag: "🇦🇺",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 13,
      name: "النمسا",
      description: null,
      code: "at",
      phone_code: "0043",
      flag: "🇦🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 14,
      name: "أذربايجان",
      description: null,
      code: "az",
      phone_code: "00994",
      flag: "🇦🇿",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 15,
      name: "البحرين",
      description: null,
      code: "bh",
      phone_code: "00973",
      flag: "🇧🇭",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 16,
      name: "بنجلاديش",
      description: null,
      code: "bd",
      phone_code: "00880",
      flag: "🇧🇩",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 17,
      name: "بيلا روسيا",
      description: null,
      code: "by",
      phone_code: "00375",
      flag: "🇧🇾",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 18,
      name: "بلجيكا",
      description: null,
      code: "be",
      phone_code: "0032",
      flag: "🇧🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 19,
      name: "بليز",
      description: null,
      code: "bz",
      phone_code: "00501",
      flag: "🇧🇿",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 20,
      name: "بنين",
      description: null,
      code: "bj",
      phone_code: "00229",
      flag: "🇧🇯",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 21,
      name: "بوتان",
      description: null,
      code: "bt",
      phone_code: "00975",
      flag: "🇧🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 22,
      name: "بوليفيا",
      description: null,
      code: "bo",
      phone_code: "00591",
      flag: "🇧🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 23,
      name: "بونير، سانت ستاتيوس و سابا",
      description: null,
      code: "bq",
      phone_code: "00599",
      flag: "🇧🇶",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 24,
      name: "البوسنة والهرسك",
      description: null,
      code: "ba",
      phone_code: "00387",
      flag: "🇧🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 25,
      name: "بوتسوانا",
      description: null,
      code: "bw",
      phone_code: "00267",
      flag: "🇧🇼",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 26,
      name: "جزيرة بوفيت",
      description: null,
      code: "bv",
      phone_code: "000055",
      flag: "🇧🇻",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 27,
      name: "البرازيل",
      description: null,
      code: "br",
      phone_code: "0055",
      flag: "🇧🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 28,
      name: "المقاطعة البريطانية بالمحيط الهندي",
      description: null,
      code: "io",
      phone_code: "00246",
      flag: "🇮🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 29,
      name: "بروني",
      description: null,
      code: "bn",
      phone_code: "00673",
      flag: "🇧🇳",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 30,
      name: "بلغاريا",
      description: null,
      code: "bg",
      phone_code: "00359",
      flag: "🇧🇬",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 31,
      name: "بوركينا فاسو",
      description: null,
      code: "bf",
      phone_code: "00226",
      flag: "🇧🇫",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 32,
      name: "بوروندي",
      description: null,
      code: "bi",
      phone_code: "00257",
      flag: "🇧🇮",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 33,
      name: "كمبوديا",
      description: null,
      code: "kh",
      phone_code: "00855",
      flag: "🇰🇭",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 34,
      name: "الكاميرون",
      description: null,
      code: "cm",
      phone_code: "00237",
      flag: "🇨🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 35,
      name: "كندا",
      description: null,
      code: "ca",
      phone_code: "001",
      flag: "🇨🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 36,
      name: "الرأس الأخضر",
      description: null,
      code: "cv",
      phone_code: "00238",
      flag: "🇨🇻",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 37,
      name: "جمهورية أفريقيا المركزية",
      description: null,
      code: "cf",
      phone_code: "00236",
      flag: "🇨🇫",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 38,
      name: "تشاد",
      description: null,
      code: "td",
      phone_code: "00235",
      flag: "🇹🇩",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 39,
      name: "شيلي",
      description: null,
      code: "cl",
      phone_code: "0056",
      flag: "🇨🇱",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 40,
      name: "الصين",
      description: null,
      code: "cn",
      phone_code: "0086",
      flag: "🇨🇳",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 41,
      name: "جزيرة الكريسمس",
      description: null,
      code: "cx",
      phone_code: "0061",
      flag: "🇨🇽",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 42,
      name: "جزر كوكوس",
      description: null,
      code: "cc",
      phone_code: "0061",
      flag: "🇨🇨",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 43,
      name: "كولومبيا",
      description: null,
      code: "co",
      phone_code: "0057",
      flag: "🇨🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 44,
      name: "كوموروس",
      description: null,
      code: "km",
      phone_code: "00269",
      flag: "🇰🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 45,
      name: "الكونغو",
      description: null,
      code: "cg",
      phone_code: "00242",
      flag: "🇨🇬",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 46,
      name: "جزر كوك",
      description: null,
      code: "ck",
      phone_code: "00682",
      flag: "🇨🇰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 47,
      name: "كوستاريكا",
      description: null,
      code: "cr",
      phone_code: "00506",
      flag: "🇨🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 48,
      name: "ساحل العاج",
      description: null,
      code: "ci",
      phone_code: "00225",
      flag: "🇨🇮",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 49,
      name: "كرواتيا",
      description: null,
      code: "hr",
      phone_code: "00385",
      flag: "🇭🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 50,
      name: "كوبا",
      description: null,
      code: "cu",
      phone_code: "0053",
      flag: "🇨🇺",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 51,
      name: "كوراشاو",
      description: null,
      code: "cw",
      phone_code: "00599",
      flag: "🇨🇼",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 52,
      name: "قبرص",
      description: null,
      code: "cy",
      phone_code: "00357",
      flag: "🇨🇾",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 53,
      name: "جمهورية التشيك",
      description: null,
      code: "cz",
      phone_code: "00420",
      flag: "🇨🇿",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 54,
      name: "جمهورية الكونغو الديموقراطية",
      description: null,
      code: "cd",
      phone_code: "00243",
      flag: "🇨🇩",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 55,
      name: "الدنمارك",
      description: null,
      code: "dk",
      phone_code: "0045",
      flag: "🇩🇰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 56,
      name: "جيبوتي",
      description: null,
      code: "dj",
      phone_code: "00253",
      flag: "🇩🇯",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 57,
      name: "تيمور الشرقية",
      description: null,
      code: "tl",
      phone_code: "00670",
      flag: "🇹🇱",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 58,
      name: "الإكوادور",
      description: null,
      code: "ec",
      phone_code: "00593",
      flag: "🇪🇨",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 59,
      name: "السلفادور",
      description: null,
      code: "sv",
      phone_code: "00503",
      flag: "🇸🇻",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 60,
      name: "غينيا الاستوائية",
      description: null,
      code: "gq",
      phone_code: "00240",
      flag: "🇬🇶",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 61,
      name: "إريتريا",
      description: null,
      code: "er",
      phone_code: "00291",
      flag: "🇪🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 62,
      name: "أستونيا",
      description: null,
      code: "ee",
      phone_code: "00372",
      flag: "🇪🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 63,
      name: "إثيوبيا",
      description: null,
      code: "et",
      phone_code: "00251",
      flag: "🇪🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 64,
      name: "جزر فولكلاند",
      description: null,
      code: "fk",
      phone_code: "00500",
      flag: "🇫🇰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 65,
      name: "جزر الفارو",
      description: null,
      code: "fo",
      phone_code: "00298",
      flag: "🇫🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 66,
      name: "جزر فيجي",
      description: null,
      code: "fj",
      phone_code: "00679",
      flag: "🇫🇯",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 67,
      name: "فنلندا",
      description: null,
      code: "fi",
      phone_code: "00358",
      flag: "🇫🇮",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 68,
      name: "فرنسا",
      description: null,
      code: "fr",
      phone_code: "0033",
      flag: "🇫🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 69,
      name: "غينيا الفرنسية",
      description: null,
      code: "gf",
      phone_code: "00594",
      flag: "🇬🇫",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 70,
      name: "بولينيزيا الفرنسية",
      description: null,
      code: "pf",
      phone_code: "00689",
      flag: "🇵🇫",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 71,
      name: "المقاطعات الجنوبية الفرنسية",
      description: null,
      code: "tf",
      phone_code: "00262",
      flag: "🇹🇫",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 72,
      name: "الجابون",
      description: null,
      code: "ga",
      phone_code: "00241",
      flag: "🇬🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 73,
      name: "جامبيا",
      description: null,
      code: "gm",
      phone_code: "00220",
      flag: "🇬🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 74,
      name: "جورجيا",
      description: null,
      code: "ge",
      phone_code: "00995",
      flag: "🇬🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 75,
      name: "ألمانيا",
      description: null,
      code: "de",
      phone_code: "0049",
      flag: "🇩🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 76,
      name: "غانا",
      description: null,
      code: "gh",
      phone_code: "00233",
      flag: "🇬🇭",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 77,
      name: "جبل طارق",
      description: null,
      code: "gi",
      phone_code: "00350",
      flag: "🇬🇮",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 78,
      name: "اليونان",
      description: null,
      code: "gr",
      phone_code: "0030",
      flag: "🇬🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 79,
      name: "جرينلاند",
      description: null,
      code: "gl",
      phone_code: "00299",
      flag: "🇬🇱",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 80,
      name: "جوادلوب",
      description: null,
      code: "gp",
      phone_code: "00590",
      flag: "🇬🇵",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 81,
      name: "جواتيمالا",
      description: null,
      code: "gt",
      phone_code: "00502",
      flag: "🇬🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 82,
      name: "غينيا",
      description: null,
      code: "gn",
      phone_code: "00224",
      flag: "🇬🇳",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 83,
      name: "غينيا بيساو",
      description: null,
      code: "gw",
      phone_code: "00245",
      flag: "🇬🇼",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 84,
      name: "غويانا",
      description: null,
      code: "gy",
      phone_code: "00592",
      flag: "🇬🇾",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 85,
      name: "هايتي",
      description: null,
      code: "ht",
      phone_code: "00509",
      flag: "🇭🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 86,
      name: "جزيرة هيرد وجزر مكدونالد",
      description: null,
      code: "hm",
      phone_code: "00672",
      flag: "🇭🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 87,
      name: "الهندوراس",
      description: null,
      code: "hn",
      phone_code: "00504",
      flag: "🇭🇳",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 88,
      name: "هونج كونج",
      description: null,
      code: "hk",
      phone_code: "00852",
      flag: "🇭🇰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 89,
      name: "هنغاريا",
      description: null,
      code: "hu",
      phone_code: "0036",
      flag: "🇭🇺",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 90,
      name: "آيسلندا",
      description: null,
      code: "is",
      phone_code: "00354",
      flag: "🇮🇸",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 91,
      name: "الهند",
      description: null,
      code: "in",
      phone_code: "0091",
      flag: "🇮🇳",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 92,
      name: "إندونيسيا",
      description: null,
      code: "id",
      phone_code: "0062",
      flag: "🇮🇩",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 93,
      name: "إيران",
      description: null,
      code: "ir",
      phone_code: "0098",
      flag: "🇮🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 94,
      name: "العراق",
      description: null,
      code: "iq",
      phone_code: "00964",
      flag: "🇮🇶",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 95,
      name: "أيرلندا",
      description: null,
      code: "ie",
      phone_code: "00353",
      flag: "🇮🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 96,
      name: "إيطاليا",
      description: null,
      code: "it",
      phone_code: "0039",
      flag: "🇮🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 97,
      name: "اليابان",
      description: null,
      code: "jp",
      phone_code: "0081",
      flag: "🇯🇵",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 98,
      name: "الأردن",
      description: null,
      code: "jo",
      phone_code: "00962",
      flag: "🇯🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 99,
      name: "كزاخستان",
      description: null,
      code: "kz",
      phone_code: "007",
      flag: "🇰🇿",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 100,
      name: "كينيا",
      description: null,
      code: "ke",
      phone_code: "00254",
      flag: "🇰🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 101,
      name: "كيريباتي",
      description: null,
      code: "ki",
      phone_code: "00686",
      flag: "🇰🇮",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 102,
      name: "كوسوفو",
      description: null,
      code: "xk",
      phone_code: "00383",
      flag: "🇽🇰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 103,
      name: "الكويت",
      description: null,
      code: "kw",
      phone_code: "00965",
      flag: "🇰🇼",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 104,
      name: "كيرجزستان",
      description: null,
      code: "kg",
      phone_code: "00996",
      flag: "🇰🇬",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 105,
      name: "ﻻوس",
      description: null,
      code: "la",
      phone_code: "00856",
      flag: "🇱🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 106,
      name: "ﻻتفيا",
      description: null,
      code: "lv",
      phone_code: "00371",
      flag: "🇱🇻",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 107,
      name: "لبنان",
      description: null,
      code: "lb",
      phone_code: "00961",
      flag: "🇱🇧",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 108,
      name: "لسوزو",
      description: null,
      code: "ls",
      phone_code: "00266",
      flag: "🇱🇸",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 109,
      name: "ليبيريا",
      description: null,
      code: "lr",
      phone_code: "00231",
      flag: "🇱🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 110,
      name: "ليبيا",
      description: null,
      code: "ly",
      phone_code: "00218",
      flag: "🇱🇾",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 111,
      name: "ليختنشتاين",
      description: null,
      code: "li",
      phone_code: "00423",
      flag: "🇱🇮",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 112,
      name: "لتوانيا",
      description: null,
      code: "lt",
      phone_code: "00370",
      flag: "🇱🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 113,
      name: "لوكسيمبورج",
      description: null,
      code: "lu",
      phone_code: "00352",
      flag: "🇱🇺",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 114,
      name: "مكاو",
      description: null,
      code: "mo",
      phone_code: "00853",
      flag: "🇲🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 115,
      name: "مقدونيا",
      description: null,
      code: "mk",
      phone_code: "00389",
      flag: "🇲🇰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 116,
      name: "مدغشقر",
      description: null,
      code: "mg",
      phone_code: "00261",
      flag: "🇲🇬",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 117,
      name: "مالاوي",
      description: null,
      code: "mw",
      phone_code: "00265",
      flag: "🇲🇼",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 118,
      name: "ماليزيا",
      description: null,
      code: "my",
      phone_code: "0060",
      flag: "🇲🇾",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 119,
      name: "المالديف",
      description: null,
      code: "mv",
      phone_code: "00960",
      flag: "🇲🇻",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 120,
      name: "مالي",
      description: null,
      code: "ml",
      phone_code: "00223",
      flag: "🇲🇱",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 121,
      name: "مالطا",
      description: null,
      code: "mt",
      phone_code: "00356",
      flag: "🇲🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 122,
      name: "جزر مارشال",
      description: null,
      code: "mh",
      phone_code: "00692",
      flag: "🇲🇭",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 123,
      name: "مارتينيك",
      description: null,
      code: "mq",
      phone_code: "00596",
      flag: "🇲🇶",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 124,
      name: "موريتانيا",
      description: null,
      code: "mr",
      phone_code: "00222",
      flag: "🇲🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 125,
      name: "موريشيوس",
      description: null,
      code: "mu",
      phone_code: "00230",
      flag: "🇲🇺",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 126,
      name: "مايوت",
      description: null,
      code: "yt",
      phone_code: "00262",
      flag: "🇾🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 127,
      name: "المكسيك",
      description: null,
      code: "mx",
      phone_code: "0052",
      flag: "🇲🇽",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 128,
      name: "ميكرونيزيا",
      description: null,
      code: "fm",
      phone_code: "00691",
      flag: "🇫🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 129,
      name: "مولدوفا",
      description: null,
      code: "md",
      phone_code: "00373",
      flag: "🇲🇩",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 130,
      name: "موناكو",
      description: null,
      code: "mc",
      phone_code: "00377",
      flag: "🇲🇨",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 131,
      name: "منغوليا",
      description: null,
      code: "mn",
      phone_code: "00976",
      flag: "🇲🇳",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 132,
      name: "منتينجرو",
      description: null,
      code: "me",
      phone_code: "00382",
      flag: "🇲🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 133,
      name: "المغرب",
      description: null,
      code: "ma",
      phone_code: "00212",
      flag: "🇲🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 134,
      name: "موزامبيق",
      description: null,
      code: "mz",
      phone_code: "00258",
      flag: "🇲🇿",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 135,
      name: "ميانمار",
      description: null,
      code: "mm",
      phone_code: "0095",
      flag: "🇲🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 136,
      name: "ناميبيا",
      description: null,
      code: "na",
      phone_code: "00264",
      flag: "🇳🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 137,
      name: "ناورو",
      description: null,
      code: "nr",
      phone_code: "00674",
      flag: "🇳🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 138,
      name: "نيبال",
      description: null,
      code: "np",
      phone_code: "00977",
      flag: "🇳🇵",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 139,
      name: "هولندا",
      description: null,
      code: "nl",
      phone_code: "0031",
      flag: "🇳🇱",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 140,
      name: "كاليدونيا الجديدة",
      description: null,
      code: "nc",
      phone_code: "00687",
      flag: "🇳🇨",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 141,
      name: "نيوزيلاندا",
      description: null,
      code: "nz",
      phone_code: "0064",
      flag: "🇳🇿",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 142,
      name: "نيكاراجوا",
      description: null,
      code: "ni",
      phone_code: "00505",
      flag: "🇳🇮",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 143,
      name: "النيجر",
      description: null,
      code: "ne",
      phone_code: "00227",
      flag: "🇳🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 144,
      name: "نيجيريا",
      description: null,
      code: "ng",
      phone_code: "00234",
      flag: "🇳🇬",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 145,
      name: "نيوي",
      description: null,
      code: "nu",
      phone_code: "00683",
      flag: "🇳🇺",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 146,
      name: "جزيرة نورفوك",
      description: null,
      code: "nf",
      phone_code: "00672",
      flag: "🇳🇫",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 147,
      name: "كوريا الشمالية",
      description: null,
      code: "kp",
      phone_code: "00850",
      flag: "🇰🇵",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 148,
      name: "النرويج",
      description: null,
      code: "no",
      phone_code: "0047",
      flag: "🇳🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 149,
      name: "عمُّان",
      description: null,
      code: "om",
      phone_code: "00968",
      flag: "🇴🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 150,
      name: "باكستان",
      description: null,
      code: "pk",
      phone_code: "0092",
      flag: "🇵🇰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 151,
      name: "بالاو",
      description: null,
      code: "pw",
      phone_code: "00680",
      flag: "🇵🇼",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 152,
      name: "فلسطين",
      description: null,
      code: "ps",
      phone_code: "00970",
      flag: "🇵🇸",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 153,
      name: "بنما",
      description: null,
      code: "pa",
      phone_code: "00507",
      flag: "🇵🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 154,
      name: "بابوا غينيا الجديدة",
      description: null,
      code: "pg",
      phone_code: "00675",
      flag: "🇵🇬",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 155,
      name: "باراجواي",
      description: null,
      code: "py",
      phone_code: "00595",
      flag: "🇵🇾",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 156,
      name: "بيرو",
      description: null,
      code: "pe",
      phone_code: "0051",
      flag: "🇵🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 157,
      name: "الفلبين",
      description: null,
      code: "ph",
      phone_code: "0063",
      flag: "🇵🇭",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 158,
      name: "جزيرة بيتكيرن",
      description: null,
      code: "pn",
      phone_code: "00870",
      flag: "🇵🇳",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 159,
      name: "بولندا",
      description: null,
      code: "pl",
      phone_code: "0048",
      flag: "🇵🇱",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 160,
      name: "البرتغال",
      description: null,
      code: "pt",
      phone_code: "00351",
      flag: "🇵🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 161,
      name: "قطر",
      description: null,
      code: "qa",
      phone_code: "00974",
      flag: "🇶🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 162,
      name: "ريونيون",
      description: null,
      code: "re",
      phone_code: "00262",
      flag: "🇷🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 163,
      name: "رومانيا",
      description: null,
      code: "ro",
      phone_code: "0040",
      flag: "🇷🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 164,
      name: "روسيا",
      description: null,
      code: "ru",
      phone_code: "007",
      flag: "🇷🇺",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 165,
      name: "رواندا",
      description: null,
      code: "rw",
      phone_code: "00250",
      flag: "🇷🇼",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 166,
      name: "سانت هيلينا",
      description: null,
      code: "sh",
      phone_code: "00290",
      flag: "🇸🇭",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 167,
      name: "سانت بيري ومكويلون",
      description: null,
      code: "pm",
      phone_code: "00508",
      flag: "🇵🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 168,
      name: "سانت بارتيليمي",
      description: null,
      code: "bl",
      phone_code: "00590",
      flag: "🇧🇱",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 169,
      name: "سان مارتن (الجزء الفرنسي)",
      description: null,
      code: "mf",
      phone_code: "00590",
      flag: "🇲🇫",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 170,
      name: "ساموا",
      description: null,
      code: "ws",
      phone_code: "00685",
      flag: "🇼🇸",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 171,
      name: "سان مارينو",
      description: null,
      code: "sm",
      phone_code: "00378",
      flag: "🇸🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 172,
      name: "ساو تومي وبرينسيبي",
      description: null,
      code: "st",
      phone_code: "00239",
      flag: "🇸🇹",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 173,
      name: "السنغال",
      description: null,
      code: "sn",
      phone_code: "00221",
      flag: "🇸🇳",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 174,
      name: "صربيا",
      description: null,
      code: "rs",
      phone_code: "00381",
      flag: "🇷🇸",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 175,
      name: "سيشل",
      description: null,
      code: "sc",
      phone_code: "00248",
      flag: "🇸🇨",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 176,
      name: "سيراليون",
      description: null,
      code: "sl",
      phone_code: "00232",
      flag: "🇸🇱",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 177,
      name: "سنغافورة",
      description: null,
      code: "sg",
      phone_code: "0065",
      flag: "🇸🇬",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 178,
      name: "سان مارتن (الجزء الهولندي)",
      description: null,
      code: "sx",
      phone_code: "001721",
      flag: "🇸🇽",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 179,
      name: "سلوفاكيا",
      description: null,
      code: "sk",
      phone_code: "00421",
      flag: "🇸🇰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 180,
      name: "سلوفينيا",
      description: null,
      code: "si",
      phone_code: "00386",
      flag: "🇸🇮",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 181,
      name: "جزر سليمان",
      description: null,
      code: "sb",
      phone_code: "00677",
      flag: "🇸🇧",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 182,
      name: "الصومال",
      description: null,
      code: "so",
      phone_code: "00252",
      flag: "🇸🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 183,
      name: "جنوب أفريقيا",
      description: null,
      code: "za",
      phone_code: "0027",
      flag: "🇿🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 184,
      name: "جوجيا الجنوبية",
      description: null,
      code: "gs",
      phone_code: "00500",
      flag: "🇬🇸",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 185,
      name: "كوريا الجنوبية",
      description: null,
      code: "kr",
      phone_code: "0082",
      flag: "🇰🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 186,
      name: "السودان الجنوبية",
      description: null,
      code: "ss",
      phone_code: "00211",
      flag: "🇸🇸",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 187,
      name: "إسبانيا",
      description: null,
      code: "es",
      phone_code: "0034",
      flag: "🇪🇸",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 188,
      name: "سريلانكا",
      description: null,
      code: "lk",
      phone_code: "0094",
      flag: "🇱🇰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 189,
      name: "السودان",
      description: null,
      code: "sd",
      phone_code: "00249",
      flag: "🇸🇩",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 190,
      name: "سورينام",
      description: null,
      code: "sr",
      phone_code: "00597",
      flag: "🇸🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 191,
      name: "جزر سفالبارد وجان ماين",
      description: null,
      code: "sj",
      phone_code: "0047",
      flag: "🇸🇯",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 192,
      name: "سوازيلاند",
      description: null,
      code: "sz",
      phone_code: "00268",
      flag: "🇸🇿",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 193,
      name: "السويد",
      description: null,
      code: "se",
      phone_code: "0046",
      flag: "🇸🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 194,
      name: "سويسرا",
      description: null,
      code: "ch",
      phone_code: "0041",
      flag: "🇨🇭",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 195,
      name: "سوريا",
      description: null,
      code: "sy",
      phone_code: "00963",
      flag: "🇸🇾",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 196,
      name: "تايوان",
      description: null,
      code: "tw",
      phone_code: "00886",
      flag: "🇹🇼",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 197,
      name: "طاجيكستان",
      description: null,
      code: "tj",
      phone_code: "00992",
      flag: "🇹🇯",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 198,
      name: "تانزانيا",
      description: null,
      code: "tz",
      phone_code: "00255",
      flag: "🇹🇿",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 199,
      name: "تايلاند",
      description: null,
      code: "th",
      phone_code: "0066",
      flag: "🇹🇭",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 200,
      name: "توجو",
      description: null,
      code: "tg",
      phone_code: "00228",
      flag: "🇹🇬",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 201,
      name: "توكيلاو",
      description: null,
      code: "tk",
      phone_code: "00690",
      flag: "🇹🇰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 202,
      name: "تونجا",
      description: null,
      code: "to",
      phone_code: "00676",
      flag: "🇹🇴",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 203,
      name: "تونس",
      description: null,
      code: "tn",
      phone_code: "00216",
      flag: "🇹🇳",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 204,
      name: "تركيا",
      description: null,
      code: "tr",
      phone_code: "0090",
      flag: "🇹🇷",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 205,
      name: "تركمنستان",
      description: null,
      code: "tm",
      phone_code: "00993",
      flag: "🇹🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 206,
      name: "توالو",
      description: null,
      code: "tv",
      phone_code: "00688",
      flag: "🇹🇻",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 207,
      name: "أوغندا",
      description: null,
      code: "ug",
      phone_code: "00256",
      flag: "🇺🇬",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 208,
      name: "أوكرانيا",
      description: null,
      code: "ua",
      phone_code: "00380",
      flag: "🇺🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 209,
      name: "الإمارات العربية المتحدة",
      description: null,
      code: "ae",
      phone_code: "00971",
      flag: "🇦🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 210,
      name: "المملكة المتحدة",
      description: null,
      code: "gb",
      phone_code: "0044",
      flag: "🇬🇧",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 211,
      name: "الولايات المتحدة",
      description: null,
      code: "us",
      phone_code: "001",
      flag: "🇺🇸",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 212,
      name: "جزر الولايات المتحدة البعيدة الصغرى",
      description: null,
      code: "um",
      phone_code: "001",
      flag: "🇺🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 213,
      name: "أورجواي",
      description: null,
      code: "uy",
      phone_code: "00598",
      flag: "🇺🇾",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 214,
      name: "أوزبكستان",
      description: null,
      code: "uz",
      phone_code: "00998",
      flag: "🇺🇿",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 215,
      name: "فانواتو",
      description: null,
      code: "vu",
      phone_code: "00678",
      flag: "🇻🇺",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 216,
      name: "الفاتيكان",
      description: null,
      code: "va",
      phone_code: "00379",
      flag: "🇻🇦",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 217,
      name: "فينزويلا",
      description: null,
      code: "ve",
      phone_code: "0058",
      flag: "🇻🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 218,
      name: "فيتنام",
      description: null,
      code: "vn",
      phone_code: "0084",
      flag: "🇻🇳",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 219,
      name: "جزر واليس وفوتونا",
      description: null,
      code: "wf",
      phone_code: "00681",
      flag: "🇼🇫",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 220,
      name: "الصحراء الغربية",
      description: null,
      code: "eh",
      phone_code: "00212",
      flag: "🇪🇭",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 221,
      name: "اليمن",
      description: null,
      code: "ye",
      phone_code: "00967",
      flag: "🇾🇪",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 222,
      name: "زامبيا",
      description: null,
      code: "zm",
      phone_code: "00260",
      flag: "🇿🇲",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 223,
      name: "زيمبابوي",
      description: null,
      code: "zw",
      phone_code: "00263",
      flag: "🇿🇼",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 224,
      name: "India",
      description: "",
      code: "FLK",
      phone_code: "00396",
      flag: "😰",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 225,
      name: "Guernsey",
      description: "",
      code: "BFA",
      phone_code: "00867",
      flag: "😔",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 226,
      name: "Sao Tome and Principe",
      description: "",
      code: "LBR",
      phone_code: "00158",
      flag: "😒",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 227,
      name: "New Zealand",
      description: "",
      code: "USA",
      phone_code: "00567",
      flag: "😘",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
    {
      id: 228,
      name: "Cyprus",
      description: "",
      code: "MCO",
      phone_code: "00221",
      flag: "😃",
      phone_available: true,
      target_available: false,
      destination_available: false,
    },
  ],
});

export const mutations = {
  SET_COUNTRIES(state, payload) {
    state.countries = payload;
  },
};
export const actions = {
  async setCountries({ commit }) {
    const res = await this.$http.get({
      resource: "countries",
      query: { simple: true, pagination: "all" },
    });
    const countries = res.data.data;

    const saudi = countries.filter((country) => country.phone_code === "00966");
    const filteredCountries = countries.filter(
      (country) => country.phone_code !== "00966"
    );
    const newCountries = [...saudi, ...filteredCountries];

    commit("SET_COUNTRIES", newCountries);
    return Promise.resolve();
  },
};

export const getters = {
  getCountries(state) {
    return state.countries;
  },
};
